#!/usr/bin/env python3

from lib.cli.client_cli import parse_download_arguments
from lib.client import download


def main():
    download(parse_download_arguments())


if __name__ == "__main__":
    main()